services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    command: "start-dev --import-realm"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/import-realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - "8180:8080"
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=produtosada
      - POSTGRES_USER=grupo6ada
      - POSTGRES_PASSWORD=grupo6ada
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - simulador-net
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - simulador-net
networks:
  simulador-net:
    driver: bridge